Repository yourteacher-org/yourteacher-fe, pull requests merged in 2024-10, with the labels that each got.

#44 [style] 헤더 호버 css 수정
  src/assets/icon/arrow-group.svg
  src/assets/icon/arrow-user.svg
  src/assets/icon/arrow-user2.svg
  src/assets/icon/login-tablet.svg
  src/component/Navbar.tsx
  src/component/Page.tsx
  src/components/Navba.tsx
  src/components/Navbar.tsx
Labels: style

#46 [feat] 라우터 구조 수정 및 Navbar 반영
  .eslintrc.cjs
  src/component/Data.tsx
  src/components/BoardWrapper.tsx
  src/components/Navbar.tsx
  src/components/Page.tsx
  src/components/ProtectGuard.tsx
  src/components/ShareAndQnABoard.tsx
  src/data/board.ts
  src/hooks/useBoardSearchParams.ts
  src/layouts/BoardLayout.tsx
  src/layouts/MainLayout.tsx
  src/pages/Edu/Edu.tsx
  src/pages/Front/Front.tsx
  src/pages/Notice/Notice.tsx
  src/pages/Qna/Communication.tsx
  src/pages/Qna/Qna.tsx
  src/pages/Qna/Sharing.tsx
  src/pages/Share/Collection.tsx
  src/pages/Share/News.tsx
  src/pages/Share/Share.tsx
  src/types/board.ts
  tsconfig.json
Labels: feature

#39 [feat] 메인페이지 교육일정 섹션 구현 진행중
  src/assets/icon/date.svg
  src/assets/icon/edu.svg
  src/assets/img/date.svg
  src/assets/img/dot.svg
  src/assets/img/edu.svg
  src/assets/img/schedul-logo.svg
  src/assets/img/schedule.png
  src/data/Schedul.ts
  src/layouts/MainLayout.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/SchedulSection.tsx
  src/pages/Home/types/schedule.ts
  src/utils/mediaQuery.ts
  tsconfig.json
Labels: feature

#47 [feat] 회원 탈퇴 페이지 구현
  src/pages/Withdraw/Withdraw.tsx
Labels: feature

#49 [fix] 메인 페이지 버그 및 로그인 페이지 수정
  src/assets/img/google_text.svg
  src/assets/img/kakaotalk_text.svg
  src/assets/img/naver_text.svg
  src/component/Page.tsx
  src/components/ChevronButton.tsx
  src/components/LoginComma.tsx
  src/components/Navba.tsx
  src/components/Navbar.tsx
  src/data/header.tsx
  src/layouts/MainLayout.tsx
  src/page/About.tsx
  src/page/Communication.tsx
  src/page/Content.tsx
  src/page/Context.tsx
  src/page/Data.tsx
  src/page/Edu.tsx
  src/page/EduDate.tsx
  src/page/Faq.tsx
  src/page/Hire.tsx
  src/page/Home.tsx
  src/page/Info.tsx
  src/page/Inquire.tsx
  src/page/Login.tsx
  src/page/News.tsx
  src/page/Notice.tsx
  src/page/Program.tsx
  src/page/Search.tsx
  src/page/Share.tsx
  src/page/SignUp.tsx
  src/page/Teacher.tsx
  src/page/User.tsx
  src/pages/Home/CommunityContent.tsx
  src/pages/Home/CommunitySection.tsx
  src/pages/Home/HeroSection.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/NoticeSection.tsx
  src/pages/Home/RecruitSection.tsx
  src/pages/Home/SchedulSection.tsx
  src/pages/Home/SearchwordSection.tsx
Labels: bug
