Repository yourteacher-org/yourteacher-fe, pull requests merged in 2024-03, with the labels that each got.

#27 [chore] Create autoDeploys.yml
  .github/workflows/autoDeploys.yml
Labels: feature

#23 [feat] 공지사항 섹션 구현
  src/assets/icon/two-circles.svg
  src/components/Button.tsx
  src/layouts/MainLayout.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/NoticeSection.tsx
  tailwind.config.js
Labels: feature

#24 [feat] 메인페이지 중 히어로, 채용공고 섹션 모바일 디자인 적용
  src/assets/img/lg-bg-1.png
  src/assets/img/lg-bg-2.png
  src/assets/img/lg-bg-3.png
  src/assets/img/sm-bg-1.png
  src/assets/img/sm-bg-2.png
  src/assets/img/sm-bg-3.png
  src/assets/img/xl-bg-1.png
  src/assets/img/xl-bg-2.png
  src/assets/img/xl-bg-3.png
  src/data/main.ts
  src/pages/Home/HeroSection.tsx
  src/pages/Home/RecruitSection.tsx
  src/pages/Home/Slide.tsx
  tailwind.config.js
Labels: feature

#26 [feat] Footer 컴포넌트 태블릿, 모바일 반응형 디자인 적용
  src/layouts/Footer.tsx
  tailwind.config.js
Labels: style

#30 [feat]메인페이지 중 인기검색어 섹션 구현과 태블릿,모바일 반응형 디자인
  src/assets/img/ZoomClick.png
  src/layouts/MainLayout.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/SearchwordSection.tsx
Labels: feature

#33 [feat] 메인페이지 자료방/소통방 섹션 구현
  src/components/ChevronButton.tsx
  src/constants/animation.ts
  src/data/main.ts
  src/pages/Home/CommunityContent.tsx
  src/pages/Home/CommunitySection.tsx
  src/pages/Home/Home.tsx
  src/utils/formatter.ts
  tailwind.config.js
  tsconfig.json
Labels: feature

#31 [fix]zoom 아이콘 이미지 파일 svg로 변경과 디자인, 반응형 수정 및 추가
  public/vite.svg
  src/assets/img/zoom.svg
  src/data/Render.ts
  src/data/Search.ts
  src/layouts/MainLayout.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/SearchwordSection.tsx
  tailwind.config.js
Labels: fix

#35 메인페이지 섹션별 버그 수정 (1)
  src/layouts/MainLayout.tsx
  src/pages/Home/HeroSection.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/NoticeSection.tsx
  src/pages/Home/RecruitSection.tsx
  src/pages/Home/SearchwordSection.tsx
Labels: bug, fix
